on:
  push:
    branches:
      - main
name: Deploy branch to Chalice
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest -c pytest.ini
      - name: Chalice deploy
        run: |
          pip install -r requirements.txt
          pip install --target=./vendor frozenlist==1.3.3 multidict==6.0.4 yarl==1.9.2 aiohttp==3.8.4
          chalice deploy --stage dev
        env:
          WORKING_DIRECTORY: backend/chalice
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ca-central-1
